services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://host.docker.internal:8080/api
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
    command: npm start
