version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8080/api
    command: npm start

# To run:
# $ docker-compose -f docker-compose.yml -f docker-compose.dev.yml up