### 1. Register a new user
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "strongpassword",
  "student_id": "ST12345",
  "first_name": "ادمین",
  "last_name": "ادمینی",
  "university_id": "00000000-0000-4000-a000-000000000001",
  "faculty_id": "00000000-0000-4000-a000-000000000002",
  "gender": "male"
}


### 2. Change `email_verified` in database to true (also if they are admin, change `is_admin` to true)

### 3. Login and get token
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "strongpassword"
}

### 4. Set the access token
@auth_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMmExZmQyN2EtZTYyYS00ZGM4LWE4NWQtNmZlN2NlNTk4MDlmIiwic2NwIjpbImFkbWluLWRhc2hib2FyZCJdLCJpc3MiOiJ0ZXJtdXN0YXQiLCJzdWIiOiIyYTFmZDI3YS1lNjJhLTRkYzgtYTg1ZC02ZmU3Y2U1OTgwOWYiLCJleHAiOjE3NDczNDI2NzYsIm5iZiI6MTc0NjczNzg3NiwiaWF0IjoxNzQ2NzM3ODc2fQ.FNB56hd1DwAME-qViUM_epYZrt9pxXeLNWOi77qe0bs

### 5. Get current user info
GET http://localhost:8080/api/v1/user/me
Authorization: Bearer {{auth_token}}
Content-Type: application/json
