### [get token by login as an admin user]
@auth_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiN2RlNzY4YjgtOWJlMS00NDVmLWJiZWMtMzQ5OTBjZTc0NGYxIiwiaXNzIjoidGVybXVzdGF0Iiwic3ViIjoiN2RlNzY4YjgtOWJlMS00NDVmLWJiZWMtMzQ5OTBjZTc0NGYxIiwiZXhwIjoxNzQ1ODAzMTI0LCJuYmYiOjE3NDU2MzAzMjQsImlhdCI6MTc0NTYzMDMyNH0.9Ph-AVgoLNf5J5r6jk-Cw_ovAoMIDFJ2SNbSb7Nfmf8

### Add universities
### Kharazmi
POST http://localhost:8080/api/v1/admin/universities
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{ "name_en": "Kharazmi", "name_fa": "خوارزمی", "is_active": true }

### Beheshti
POST http://localhost:8080/api/v1/admin/universities
Authorization: Bearer {{auth_token}}

{ "name_en": "Beheshti", "name_fa": "بهشتی", "is_active": true }