### Set base URL and admin token
@base_url = http://localhost:8080/api/v1
@auth_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMmExZmQyN2EtZTYyYS00ZGM4LWE4NWQtNmZlN2NlNTk4MDlmIiwic2NwIjpbImFkbWluLWRhc2hib2FyZCJdLCJpc3MiOiJ0ZXJtdXN0YXQiLCJzdWIiOiIyYTFmZDI3YS1lNjJhLTRkYzgtYTg1ZC02ZmU3Y2U1OTgwOWYiLCJleHAiOjE3NDczNDI2NzYsIm5iZiI6MTc0NjczNzg3NiwiaWF0IjoxNzQ2NzM3ODc2fQ.FNB56hd1DwAME-qViUM_epYZrt9pxXeLNWOi77qe0bs

### Add Kharazmi University
POST {{base_url}}/admin/universities
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name_en": "Kharazmi",
  "name_fa": "خوارزمی",
  "is_active": true
}

### Add Beheshti University
POST {{base_url}}/admin/universities
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name_en": "Beheshti",
  "name_fa": "بهشتی",
  "is_active": false
}