name: API CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yml'
  pull_request:
    branches: [ "main" ] # It's good practice to also scope PR triggers to the main branch
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        working-directory: ./api
        run: ~/go/bin/golangci-lint run ./... --timeout 5m 

      - name: Run unit-tests
        run: |
          go test -v ./...

      - name: Build API
        working-directory: ./api
        run: go build -v ./...
